version: "3.9"
services:
    app:
        build:
            dockerfile: Dockerfile.dev
            context: .
            target: dev
        ports:
            -   "80:8080"
        volumes:
            - .:/opt/app/api
